# Complete list of all available properties: https://docs.upsun.com/app/reference/
applications:
  more4nature-website:
    type: "nodejs:22"
    container_profile: BALANCED

    dependencies:
      nodejs:
        pnpm: "*"

    build:
      flavor: none

    hooks:
      build: |
        set -ex
        pnpm install --frozen-lockfile
        pnpm run build

        cp -r public .next/standalone/
        mkdir -p .next/standalone/.next
        cp -r .next/static .next/standalone/.next/

    web:
      commands:
        start: node .next/standalone/server.js

      locations:
        /:
          passthru: true
          expires: 1h
          scripts: false

    variables:
      env:
        NEXT_TELEMETRY_DISABLED: '1'
        HOSTNAME: '0.0.0.0'

    mounts:
      .next/cache:
        source: storage

routes:
  "https://{default}/":
    type: upstream
    upstream: more4nature-website:http

