name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    name: Build static site
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - uses: pnpm/action-setup@v4

      - name: Install deps
        run: pnpm install

      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: '1'
          NEXT_PUBLIC_MAILCHIMP_FORM_ACTION: ${{ vars.NEXT_PUBLIC_MAILCHIMP_FORM_ACTION }}
          NEXT_PUBLIC_MAILCHIMP_HONEYPOT_NAME: ${{ vars.NEXT_PUBLIC_MAILCHIMP_HONEYPOT_NAME }}
        run: pnpm build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
